proyectoFinal/apps/contactos/urls.py
from django.urls import path, include
from . import views

app_name='contactos'

urlpatterns = [
    
    path('', views.PrimerContacto.as_view(), name="contacto"),
]
 

proyectoFinal/apps/empr/urls.py
from django.urls import path, include
from . import views


app_name='empr'

urlpatterns = [

    path('Crear', views.CrearEmpredimiento.as_view(), name="crear_empredimiento"),

    path('Listar', views.ListarEmprendimientos.as_view(), name="listar_emprendimientos"),

    path('Detalle/<int:pk>', views.DetalleEmprendimientos.as_view(), name="detalle_emprendimiento"),

    path('Editar/<int:pk>', views.EditarEmprendimientos.as_view(), name="editar_emprendimientos"),

    path('Eliminar/<int:pk>', views.EliminarEmprendimientos.as_view(), name="eliminar_emprendimiento"),

    path('Filtrar/<str:orden>', views.FiltrarPorOrden.as_view(), name='filtrar_orden'),

    path('Filtrar/<str:nombre>/<str:orden>', views.FiltrarPorOrden.as_view(), name='filtrar_orden_cat'),




]

proyectoFinal/apps/usuarios/urls.py
from django.urls import path, include
from . import views

app_name='usuarios'

urlpatterns = [
    path('Registro', views.Registro.as_view(), name="registrar"),
]

proyectoFinal/proyectoFinal/urls.py
from django.contrib import admin
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.Home, name = 'home'),

    path('sobre_nosotros', views.Sobre_nosotros, name = 'sobre_nosotros'),

    path('contacto', views.Contacto, name = 'contacto'),



    #URLS DE AUTH
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

    #urls de usuarios
    path('usuarios/', include('apps.usuarios.urls')),

    # url de de las aplicaciones

    #url de empr
    path('emprendimientos/', include('apps.empr.urls')),

    #url de contactos
    path('contactos/', include('apps.contactos.urls')),

    path('comentarios/', include('apps.comentarios.urls')),

    path('perfil-usuario/', views.Perfil_usuario, name='perfil'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectoFinal/apps/empr/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta
# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=80)
    imagen = models.ImageField(upload_to='categorias')
    resumen = models.TextField()
    
    def __str__(self):
        return self.nombre
    
class Emprendimientos(models.Model):
    creado = models.DateTimeField(
		'creado',
		auto_now_add=True
	)
    modificado = models.DateTimeField(
		'modificado', 
		auto_now=True
	)
    titulo = models.CharField(max_length=80)
    resumen = models.TextField()
    contenido = models.TextField()
    autor = models.ForeignKey(User, on_delete = models.CASCADE)
    imagen = models.ImageField(upload_to= 'empr')
    categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE)
    
    def get_creado_naturaltime(self):
        now = timezone.now()
        diff = now - self.creado
        
        if diff < timedelta(minutes=1):
            return 'hace unos segundos'
        elif diff < timedelta(hours=1):
            minutes = diff.seconds // 60
            return f'hace {minutes} minutos'
        elif diff < timedelta(days=1):
            hours = diff.seconds // 3600
            return f'hace {hours} horas'
        elif diff < timedelta(days=30):
            days = diff.days
            return f'hace {days} días'
        else:
            return self.creado.strftime('%d de %B de %Y a las %H:%M')
        
    def get_modificado_naturaltime(self):
        now = timezone.now()
        diff = now - self.modificado
        print(diff)
        
        if diff < timedelta(minutes=1): 
            return 'hace unos segundos'
        elif diff < timedelta(hours=1):
            minutes = diff.seconds // 60
            return f'hace {minutes} minutos'
        elif diff < timedelta(days=1):
            hours = diff.seconds // 3600
            return f'hace {hours} horas'
        elif diff < timedelta(days=30):
            days = diff.days
            return f'hace {days} días'
        else:
            return self.creado.strftime('%d de %B de %Y a las %H:%M')
    
    def MisComentarios(self):
        return self.comentarios_set.all()

        
    def __str__(self):
        return self.titulo

proyectoFinal/apps/empr/forms.py
from django import forms
from .models import Emprendimientos


class Form_Alta(forms.ModelForm):

    class Meta:
        model = Emprendimientos
        fields = ('titulo','resumen','contenido','categoria','imagen' )
        labels = {
            'resumen': 'Breve Descripción',
            'contenido': 'Descripción',
        }
class Form_Modificacion(forms.ModelForm):

    class Meta:
        model = Emprendimientos
        fields = ('titulo','resumen','contenido','categoria','imagen')
        labels = {
            'resumen': 'Breve Descripción',
            'contenido': 'Descripción',
        }

proyectoFinal/apps/empr/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.dispatch import receiver
from django.db.models.signals import pre_delete
from django.shortcuts import render, redirect
import os

from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from django.urls import reverse, reverse_lazy

from .models import Emprendimientos
from .forms import Form_Alta,  Form_Modificacion

from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib import messages

from django.contrib.auth.mixins    import UserPassesTestMixin

from django.db.models import Func, F

class CrearEmpredimiento(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Emprendimientos
    form_class = Form_Alta
    template_name = 'empr/crear.html'

    def get_success_url(self):
        return reverse('empr:detalle_emprendimiento', kwargs={'pk': self.object.pk})

    def test_func(self):
        return self.request.user.is_staff

    def form_valid(self, form):
        emprendimiento = form.save(commit=False)
        emprendimiento.autor = self.request.user
        emprendimiento.save()
        messages.success(self.request, 'El emprendimiento ha sido creado exitosamente.')
        return super().form_valid(form)


    def dispatch(self, request, *args, **kwargs):
        if not self.test_func():
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def handle_no_permission(self):
        return render(self.request, 'error/403.html', {'mensaje': 'No tienes permiso para acceder a esta página.'}, status=403)





class   ListarEmprendimientos(ListView):
    model = Emprendimientos
    template_name = 'empr/listar.html'
    context_object_name = 'emprendimientos_por_categoria'

    def get(self, request, *args, **kwargs):
        emprendimiento_id = request.GET.get('emprendimiento_id')
        if emprendimiento_id:
            messages.success(request, 'El emprendimiento ha sido eliminado exitosamente.')
        return super().get(request, *args, **kwargs)

class DetalleEmprendimientos(DetailView):
    model = Emprendimientos
    template_name = 'empr/detalles.html'
    context_object_name = 'emprendimientos'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

class EditarEmprendimientos(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Emprendimientos
    form_class = Form_Modificacion
    template_name = 'empr/editar.html'

    def test_func(self):
        return self.request.user.is_staff

    def test_func_autor(self):
        emprendimiento = self.get_object()
        return self.request.user == emprendimiento.autor

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['emprendimiento_id'] = self.object.pk
        return context

    def get_success_url(self):
        emprendimiento_id = self.object.pk
        return reverse_lazy('empr:detalle_emprendimiento', kwargs={'pk': emprendimiento_id})

    def form_valid(self, form):
        messages.success(self.request, 'El emprendimiento ha sido actualizado exitosamente.')
        return super().form_valid(form)
    def dispatch(self, request, *args, **kwargs):
        if not self.test_func():
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def handle_no_permission(self):
        return render(self.request, 'error/403.html', {'mensaje': 'No tienes permiso para acceder a esta página.'}, status=403)



class EliminarEmprendimientos(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Emprendimientos
    template_name = 'empr/eliminar.html'
    success_url = reverse_lazy('empr:listar_emprendimientos')

    def test_func(self):
        return self.request.user.is_staff

    def test_func_autor(self):
        emprendimiento = self.get_object()
        return self.request.user == emprendimiento.autor
    @receiver(pre_delete, sender=Emprendimientos)
    def eliminar_imagen_emprendimiento(sender, instance, **kwargs):
        if instance.imagen:
            if os.path.isfile(instance.imagen.path):
                os.remove(instance.imagen.path)
    def delete(self, request, *args, **kwargs):
        emprendimiento = self.get_object()
        self.perform_destroy(emprendimiento)
        return redirect('empr:listar_emprendimientos', emprendimiento_id=emprendimiento.pk)

    def dispatch(self, request, *args, **kwargs):
        if not self.test_func():
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def handle_no_permission(self):
        return render(self.request, 'error/403.html', {'mensaje': 'No tienes permiso para acceder a esta página.'}, status=403)


class FiltrarPorOrden(ListView):
    model = Emprendimientos
    template_name = 'empr/filtrar-orden.html'
    context_object_name = 'emprendimientos'
    def get_queryset(self):

        nombre = self.kwargs.get('nombre')

        if nombre:
            queryset = Emprendimientos.objects.filter(categoria__nombre=nombre)
        else:
            queryset = Emprendimientos.objects.all()

        orden = self.kwargs.get('orden')
        if orden == 'asc':
            queryset = queryset.order_by('titulo')
        elif orden == 'desc':
            queryset = queryset.order_by('-titulo')
        elif orden == 'antiguedad-asc':
            queryset = queryset.order_by('creado')
        elif orden == 'antiguedad-desc':
            queryset = queryset.order_by('-creado')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre'] = self.kwargs.get('nombre')
        return context

proyectoFinal/templates/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block css %}
        {% endblock css %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css'%}">
        <title>InfoBlog</title>
    </head>
    <body>

        {% if user.is_authenticated %}

        <nav class="navbar navbar-expand-lg" data-bs-theme="dark" style="background-color: #6F2AF3;">
            <div class="container-fluid">
                <!-- Acá está el logo de nuestro blog -->
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'img/InfoBlog_Logo.png'%}" alt="Bootstrap" class="estlogo">
                </a>
                <a class="navbar-brand mb-0 h1 fw-bold" href="{% url 'home' %}" >Inicio</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'empr:listar_emprendimientos' %}">Emprendimientos</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Categorías
                            </a>
                            <ul class="dropdown-menu">
                                {%for categoria in cat_context%}
                              <li><a class="dropdown-item" href="{%url 'empr:filtrar_orden_cat' nombre=categoria.nombre orden='asc'%}">{{categoria.nombre}}</a></li>
                                {%endfor%}
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'sobre_nosotros' %}">Sobre Nosotros</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contactos:contacto' %}">Contacto</a>
                        </li>

                    </ul>

                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        {%if user.is_staff%}
                        <a href="{%url 'empr:crear_empredimiento'%}" class="btn btn-outline-light btn-sm">Crear emprendimiento</a>
                        {%endif%}
                        <a href="{% url 'perfil' %}"><button type="button" class="btn btn-light btn-sm">{{ user.username }}</button></a>
                        <a href="{% url 'logout' %}"><button type="button" class="btn btn-secondary btn-sm">Salir</button></a>
                    </div>

        {% else %}

        <nav class="navbar navbar-expand-lg" data-bs-theme="dark" style="background-color: #6F2AF3;">
            <div class="container-fluid">
                <!-- Acá está el logo de nuestro blog -->
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'img/InfoBlog_Logo.png'%}" alt="Bootstrap" class="estlogo">
                </a>
                <a class="navbar-brand mb-0 h1 fw-bold" href="{% url 'home' %}" >Inicio</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'empr:listar_emprendimientos' %}">Emprendimientos</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Categorías
                            </a>
                            <ul class="dropdown-menu">
                                {%for categoria in cat_context%}
                                <li><a class="dropdown-item" href="{%url 'empr:filtrar_orden_cat' nombre=categoria.nombre orden='asc'%}">{{categoria.nombre}}</a></li>
                                {%endfor%}
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'sobre_nosotros' %}">Sobre Nosotros</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contactos:contacto' %}">Contacto</a>
                        </li>

                    </ul>

                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <a href="{% url 'login' %}"><button type="button" class="btn btn-light btn-sm">Ingresar</button></a>
                        <a href="{% url 'usuarios:registrar' %}"><button type="button" class="btn btn-secondary btn-sm">Registrarse</button></a>
                    </div>

                    {% endif %}

                </div>
            </div>
        </nav>

       {% block contenido %}

       {% endblock contenido %}

        {% block contacto %}

       {% endblock contacto %}



       <footer><p>Diseñado y desarrollado por: Grupo 6 - Comision 1 - Informatorio</p></footer>
       {%block script%}
       {%endblock script%}
       {% autoescape off %}
       <script src="{%static 'js/swiper-bundle.min.js'%}"></script>
       <script src="{% static 'js/app1.js'%}"></script>

       {% endautoescape %}
       <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    </body>
</html>

proyectoFinal/templates/empr.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style_empr.css'%}">
{% endblock css %}

{% block contenido %}	
<div class="base">


</div>
{% endblock contenido %}

proyectoFinal/templates/index.html
{% extends 'base.html' %}
{% load static %}
{%block css%}
<link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style_empr_listar.css'%}">
{%endblock css%}
{% block contenido %}	
<div class="container" >
    <div class="row" style="margin: 0 5%;">

        <!-- Baner de presentación-->
      <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel"> 
        <div class="carousel-inner">

          {%if not cat_context%}
          <div class="carousel-item active">
            <img src="{% static 'img/empr/comercio.jpg'%}" style="width: 100%" class="d-block w-100" alt="comercial">
            <div class="carousel-caption d-none d-md-block "> 
              <h5>Emprendimiento Comercial</h5>
                <p>Negocios que se dedican a la venta de bienes o servicios al consumidores.</p>
              </div>
          </div>
          {%else%}
            {% for categoria in cat_context%}
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
              <img src="{{categoria.imagen.url}}" class="filtro d-block w-100" alt="comercial">
              <div class="carousel-caption d-none d-md-block ">
                <a href="{%url 'empr:filtrar_orden_cat' nombre=categoria.nombre orden='asc' %}" style="color:white;">   
                <h2>{{categoria.nombre}}</h2>
                  <p>{{categoria.resumen}}</p></a>
                </div>
            </div>
            {%endfor%}
          {%endif%}
           

        </div>
        {%if num_categorias >= 2%}
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
        {%endif%}
      </div>
    </div>
        <div class="row d-flex justify-content-around text-center">
            <article class="col-lg-3 col-sm-12 contador">
                <span class="number" data-value="{{num_categorias}}">0 +</span>
                <p>Categorias</p>
            </article>
            <!-- end of single number -->
            <!-- single number -->
            <article class="col-lg-3 col-sm-12 contador">
                <span class="number" data-value="{{num_emprendimientos}}">0 +</span> 
                <p>Emprendimientos</p>
            </article >
            <!-- end of single number -->
            <!-- single number -->
            <article class="col-lg-3 col-sm-12 contador">
                <span class="number" data-value="{{num_usuarios}}">0 +</span>
                <p>Usuarios Registrados</p>
            </article>
            <!-- end of single number -->
           
        </div>
        <div class="row d-flex justify-content-around text-center">
          <div class="titulo-empr" style="margin-bottom: 0;">
            <h2>Ultimos emprendimimentos</h2>
          </div>
          {%if num_emprendimientos == 0%}
          <h1>No hay Emprendimientos disponibles</h1>
          <h2>Por favor agregue 1</h2>
          {%else%}
          <div class="slide-container swiper">
            <div class="slide-content">
              <div class="card-wrapper swiper-wrapper">
                {%for emprendimimento in empr_context%}
                <div class="card swiper-slide" style="border: none;">
                  <a href="{% url 'empr:detalle_emprendimiento' emprendimimento.pk %}">
                  <div class="img-content" style="background: linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.8)) ,url({{emprendimimento.imagen.url}}); background-size: cover;">
                    <img src="{{emprendimimento.imagen.url}}" alt="foto">
                  </div>
                  <div class="card-content">
                    <h2 class="titulo">{{emprendimimento.titulo}}</h2>
							      <p class="name">{{emprendimimento.resumen}}</p>
                  </div>
                </a>
                </div>
                {%endfor%}
              </div>
            </div>
            <div class="swiper-button-next swiper-navBtn"></div>
            <div class="swiper-button-prev swiper-navBtn"></div>
            <div class="swiper-pagination"></div>
          </div>
          {%endif%}
        </div>

</div>

{% endblock contenido %}

proyectoFinal/templates/perfil.html
{% extends 'base.html' %}
{% load static %}
{%block css%}
<link rel="stylesheet" href="{% static 'css/style_filtrar.css'%}">
{%endblock css%}
{% block contenido %}

<div class="base">

    <div class="perfil">
        <div class="tarjeta">
            <div class="esty">
                <h2>{{user.username}}</h2>
            </div>
            <div class="esty borde">
                <h6>{{user.first_name|capfirst}}</h6>
                <h6>{{user.last_name|capfirst}}</h6>
            </div>
            <div class="esty borde">
                <h6>{{user.email}}</h6>
            </div>
            <div class="esty borde">
                {% if user.is_staff%}
                <h6>Usuario: Colaborador</h6>
                {% else %}
                <h6>Usuario: Espectador</h6>
                {% endif %}

            </div>


        </div>

    </div>
     {%if user.is_staff %}
    <div class="empr-cont">
        <h2 class="mis-empr">Mis Emprendimientos</h2>
        <div class="empr">
                {%for emprendimimento in empr_context%}
                {%if emprendimimento.autor|lower ==  user.username|lower%}
                    <div class="card" style="border: none;">
                        <a href="{% url 'empr:detalle_emprendimiento' emprendimimento.pk %}">

                            <div class="img-content" style="background: linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.8)) ,url({{emprendimimento.imagen.url}}); background-size: cover;">
                                <img src="{{emprendimimento.imagen.url}}" alt="foto">
                            </div>

                            <div class="card-content">
                                <h2 class="titulo">{{emprendimimento.titulo}}</h2>
                                <p class="name">{{emprendimimento.resumen}}</p>
                            </div>

                        </a>
                    </div>
                {%endif%}
                {%endfor%}
        </div>
    </div>
    {% else %}
    <div class="empr-cont">
        <h3 class="mis-empr">¿Quieres publicar tus emprendimiento? Contactanos</h3>
    </div>
     {%endif%}
</div>


{% endblock contenido %}

proyectoFinal/templates/post.html
{% extends 'base.html' %}

{% block contenido %}	

<h1>Bienvenidos a la seccion de Noticias</h1>


{% endblock contenido %}