proyectoFinal/apps/comentarios/urls.py
from django.urls import path, include
from . import views

app_name='comentarios'

urlpatterns = [
    path('Crear/<int:pk>', views.CrearComentario.as_view(), name='crear_comentario'),
    
    path('Eliminar', views.EliminarComentario.as_view(), name='eliminar_comentario'),
    
    path('Detalles', views.detalle_comentario, name="detalle_comentario"),
    
    path('Actualizar', views.ModificarComentario.as_view(), name="modificar_comentario"),
    
]

proyectoFinal/apps/empr/urls.py
from django.urls import path, include
from . import views


app_name='empr'

urlpatterns = [

    path('Crear', views.CrearEmpredimiento.as_view(), name="crear_empredimiento"),

    path('Listar', views.ListarEmprendimientos.as_view(), name="listar_emprendimientos"),

    path('Detalle/<int:pk>', views.DetalleEmprendimientos.as_view(), name="detalle_emprendimiento"),

    path('Editar/<int:pk>', views.EditarEmprendimientos.as_view(), name="editar_emprendimientos"),

    path('Eliminar/<int:pk>', views.EliminarEmprendimientos.as_view(), name="eliminar_emprendimiento"),

    path('Filtrar/<str:orden>', views.FiltrarPorOrden.as_view(), name='filtrar_orden'),

    path('Filtrar/<str:nombre>/<str:orden>', views.FiltrarPorOrden.as_view(), name='filtrar_orden_cat'),




]

proyectoFinal/apps/usuarios/urls.py
from django.urls import path, include
from . import views

app_name='usuarios'

urlpatterns = [
    path('Registro', views.Registro.as_view(), name="registrar"),
]

proyectoFinal/proyectoFinal/urls.py
from django.contrib import admin
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.Home, name = 'home'),

    path('sobre_nosotros', views.Sobre_nosotros, name = 'sobre_nosotros'),

    path('contacto', views.Contacto, name = 'contacto'),



    #URLS DE AUTH
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

    #urls de usuarios
    path('usuarios/', include('apps.usuarios.urls')),

    # url de de las aplicaciones

    #url de empr
    path('emprendimientos/', include('apps.empr.urls')),

    #url de contactos
    path('contactos/', include('apps.contactos.urls')),

    path('comentarios/', include('apps.comentarios.urls')),

    path('perfil-usuario/', views.Perfil_usuario, name='perfil'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectoFinal/apps/empr/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta
# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=80)
    imagen = models.ImageField(upload_to='categorias')
    resumen = models.TextField()
    
    def __str__(self):
        return self.nombre
    
class Emprendimientos(models.Model):
    creado = models.DateTimeField(
		'creado',
		auto_now_add=True
	)
    modificado = models.DateTimeField(
		'modificado', 
		auto_now=True
	)
    titulo = models.CharField(max_length=80)
    resumen = models.TextField()
    contenido = models.TextField()
    autor = models.ForeignKey(User, on_delete = models.CASCADE)
    imagen = models.ImageField(upload_to= 'empr')
    categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE)
    
    def get_creado_naturaltime(self):
        now = timezone.now()
        diff = now - self.creado
        
        if diff < timedelta(minutes=1):
            return 'hace unos segundos'
        elif diff < timedelta(hours=1):
            minutes = diff.seconds // 60
            return f'hace {minutes} minutos'
        elif diff < timedelta(days=1):
            hours = diff.seconds // 3600
            return f'hace {hours} horas'
        elif diff < timedelta(days=30):
            days = diff.days
            return f'hace {days} días'
        else:
            return self.creado.strftime('%d de %B de %Y a las %H:%M')
        
    def get_modificado_naturaltime(self):
        now = timezone.now()
        diff = now - self.modificado
        print(diff)
        
        if diff < timedelta(minutes=1): 
            return 'hace unos segundos'
        elif diff < timedelta(hours=1):
            minutes = diff.seconds // 60
            return f'hace {minutes} minutos'
        elif diff < timedelta(days=1):
            hours = diff.seconds // 3600
            return f'hace {hours} horas'
        elif diff < timedelta(days=30):
            days = diff.days
            return f'hace {days} días'
        else:
            return self.creado.strftime('%d de %B de %Y a las %H:%M')
    
    def MisComentarios(self):
        return self.comentarios_set.all()

        
    def __str__(self):
        return self.titulo

proyectoFinal/apps/empr/forms.py
from django import forms
from .models import Emprendimientos


class Form_Alta(forms.ModelForm):

    class Meta:
        model = Emprendimientos
        fields = ('titulo','resumen','contenido','categoria','imagen' )
        labels = {
            'resumen': 'Breve Descripción',
            'contenido': 'Descripción',
        }
class Form_Modificacion(forms.ModelForm):

    class Meta:
        model = Emprendimientos
        fields = ('titulo','resumen','contenido','categoria','imagen')
        labels = {
            'resumen': 'Breve Descripción',
            'contenido': 'Descripción',
        }

proyectoFinal/apps/empr/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.dispatch import receiver
from django.db.models.signals import pre_delete
from django.shortcuts import render, redirect
import os

from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from django.urls import reverse, reverse_lazy

from .models import Emprendimientos
from .forms import Form_Alta,  Form_Modificacion

from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib import messages

from django.contrib.auth.mixins    import UserPassesTestMixin

from django.db.models import Func, F

class CrearEmpredimiento(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Emprendimientos
    form_class = Form_Alta
    template_name = 'empr/crear.html'

    def get_success_url(self):
        return reverse('empr:detalle_emprendimiento', kwargs={'pk': self.object.pk})

    def test_func(self):
        return self.request.user.is_staff

    def form_valid(self, form):
        emprendimiento = form.save(commit=False)
        emprendimiento.autor = self.request.user
        emprendimiento.save()
        messages.success(self.request, 'El emprendimiento ha sido creado exitosamente.')
        return super().form_valid(form)


    def dispatch(self, request, *args, **kwargs):
        if not self.test_func():
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def handle_no_permission(self):
        return render(self.request, 'error/403.html', {'mensaje': 'No tienes permiso para acceder a esta página.'}, status=403)





class   ListarEmprendimientos(ListView):
    model = Emprendimientos
    template_name = 'empr/listar.html'
    context_object_name = 'emprendimientos_por_categoria'

    def get(self, request, *args, **kwargs):
        emprendimiento_id = request.GET.get('emprendimiento_id')
        if emprendimiento_id:
            messages.success(request, 'El emprendimiento ha sido eliminado exitosamente.')
        return super().get(request, *args, **kwargs)

class DetalleEmprendimientos(DetailView):
    model = Emprendimientos
    template_name = 'empr/detalles.html'
    context_object_name = 'emprendimientos'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

class EditarEmprendimientos(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Emprendimientos
    form_class = Form_Modificacion
    template_name = 'empr/editar.html'

    def test_func(self):
        return self.request.user.is_staff

    def test_func_autor(self):
        emprendimiento = self.get_object()
        return self.request.user == emprendimiento.autor

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['emprendimiento_id'] = self.object.pk
        return context

    def get_success_url(self):
        emprendimiento_id = self.object.pk
        return reverse_lazy('empr:detalle_emprendimiento', kwargs={'pk': emprendimiento_id})

    def form_valid(self, form):
        messages.success(self.request, 'El emprendimiento ha sido actualizado exitosamente.')
        return super().form_valid(form)
    def dispatch(self, request, *args, **kwargs):
        if not self.test_func():
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def handle_no_permission(self):
        return render(self.request, 'error/403.html', {'mensaje': 'No tienes permiso para acceder a esta página.'}, status=403)



class EliminarEmprendimientos(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Emprendimientos
    template_name = 'empr/eliminar.html'
    success_url = reverse_lazy('empr:listar_emprendimientos')

    def test_func(self):
        return self.request.user.is_staff

    def test_func_autor(self):
        emprendimiento = self.get_object()
        return self.request.user == emprendimiento.autor
    @receiver(pre_delete, sender=Emprendimientos)
    def eliminar_imagen_emprendimiento(sender, instance, **kwargs):
        if instance.imagen:
            if os.path.isfile(instance.imagen.path):
                os.remove(instance.imagen.path)
    def delete(self, request, *args, **kwargs):
        emprendimiento = self.get_object()
        self.perform_destroy(emprendimiento)
        return redirect('empr:listar_emprendimientos', emprendimiento_id=emprendimiento.pk)

    def dispatch(self, request, *args, **kwargs):
        if not self.test_func():
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def handle_no_permission(self):
        return render(self.request, 'error/403.html', {'mensaje': 'No tienes permiso para acceder a esta página.'}, status=403)


class FiltrarPorOrden(ListView):
    model = Emprendimientos
    template_name = 'empr/filtrar-orden.html'
    context_object_name = 'emprendimientos'
    def get_queryset(self):

        nombre = self.kwargs.get('nombre')

        if nombre:
            queryset = Emprendimientos.objects.filter(categoria__nombre=nombre)
        else:
            queryset = Emprendimientos.objects.all()

        orden = self.kwargs.get('orden')
        if orden == 'asc':
            queryset = queryset.order_by('titulo')
        elif orden == 'desc':
            queryset = queryset.order_by('-titulo')
        elif orden == 'antiguedad-asc':
            queryset = queryset.order_by('creado')
        elif orden == 'antiguedad-desc':
            queryset = queryset.order_by('-creado')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre'] = self.kwargs.get('nombre')
        return context

proyectoFinal/templates/empr/crear.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style_crear.css'%}">
{% endblock css %}

{% block contenido %}
{%for mensaje in messages%}
			<div class="alert alert-success alert-dismissible fade show" role="alert">
				 {{ mensaje }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
			{%endfor%}
<div class="base">
  <form class="contenedor" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
  <h3 class="mb-4">Crear Emprendimiento</h3>
    {{form.as_div}}
    <p><input type="submit" class="btn btn-primary btn-block" value="Confirmar"></p>
  </form>
</div>

{% endblock contenido %}

proyectoFinal/templates/empr/detalles.html
{% extends 'base.html' %}
{% block css%}
{% load static %}


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" href="{% static 'css/style_detalles.css'%}">
{%endblock%}
{% block contenido %}

<div class="base">
	<div class="contenedor">
		<div class="mensaje text-center">
			{%for mensaje in messages%}
			<div class="alert alert-success alert-dismissible fade show" role="alert">
				 {{ mensaje }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
			{%endfor%}
		</div>
		<div class="detalles">
			<h1 class="titulos">{{emprendimientos.titulo}}</h1>
			<h4 class="resumen">{{emprendimientos.resumen}}</h4>
			<div class="cont">
				<div class="cont-img">
					<img class="img-empr" src="{{emprendimientos.imagen.url}}" alt="foto de emprendimiento">
				</div>
				<p class="contenido">{{emprendimientos.contenido}}</p>
				<div class="botones">
					{%if emprendimientos.autor == user%}
						<a href="{% url 'empr:editar_emprendimientos' emprendimientos.pk%}" class="btn btn-outline-primary text-center">editar</a>
						<!-- Button trigger modal -->
							<button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop1">
								Eliminar
							  </button>

						{%endif%}
						<!-- <a href="{%url 'empr:eliminar_emprendimiento' emprendimientos.pk%}" class="btn btn-info text-center">eliminar</a> -->
						<!-- Modal -->

				</div>
			</div>
			<div class="info">
				<p class="autores">AUTOR: {{emprendimientos.autor}}</p>
				<p class="categorias">CATEGORIA: {{emprendimientos.categoria}}</p>
				{% if emprendimientos.get_modificado_naturaltime != emprendimientos.get_creado_naturaltime %}
				<p class="fecha">FECHA: {{emprendimientos.get_creado_naturaltime}}</p>
        		<p class="fecha">Editado: {{emprendimientos.get_modificado_naturaltime}}</p>
				{%else%}
				<p class="fecha">FECHA: {{emprendimientos.get_creado_naturaltime}}</p>
    			{% endif %}

			</div>
			<!-- Acá van a ir los comentarios -->

			<div class="cont-com">
				{%for com in emprendimientos.MisComentarios%}
				<div class="com">
					<div class="datos">
						<div class="nombre">
							<h5 class="usuario">{{com.usuario}}</h5>
							{% if com.get_modificado_naturaltime != com.get_creado_naturaltime %}
							<h5 class="fecha">Modificado {{ com.get_modificado_naturaltime }}</h5>
							{%else%}
							<h5 class="fecha">Creado: {{com.get_creado_naturaltime }}</h5>
							{% endif %}
						</div>
						{% if com.usuario|lower == user.username|lower%}
						<div class="opciones">
							<a class="editar abrir-modal abrir-modal-editar" href="#" data-comentario-id="{{com.pk}}" data-bs-toggle="modal" data-bs-target="#modal2">Editar</a>
							<a class="borrar abrir-modal" href="#" data-comentario-id="{{ com.pk }}" data-bs-toggle="modal" data-bs-target="#modal1">Borrar</a>
						</div>
						{%elif user.username|lower == emprendimientos.autor|lower%}
						<div class="opciones">
						<a class="borrar abrir-modal" href="#" data-comentario-id="{{ com.pk }}" data-bs-toggle="modal" data-bs-target="#modal1">Borrar</a>
						</div>
						{%endif%}
					</div>
					<div class="comentario">
						<p>{{com.texto}}</p>
					</div>
				</div>
				{%endfor%}

				{% if user.is_authenticated %}
				<form class="com" action="{% url 'comentarios:crear_comentario' emprendimientos.pk %}" method="post" id="comentario-form">
					{% csrf_token %}
					<div class="enviar-com">
						<div class="comentar-post">
							<textarea type="text" placeholder="Escribe un comentario" class="comentarios-textarea" name="comentario" id="textarea-comentario"></textarea>
						</div>
						<div class="boton-enviar">
							<button type="submit" class="btn btn-outline-primary text-center">Enviar</button>
						</div>
					</div>
				</form>
				{%else%}
				<div class="boton-comentario">
						<h3>¿Quieres realizar un comentario?</h3>
						<a href="{%url 'login'%}"><button class="btn btn-outline-primary text-center">Loguearme</button>
						<a href="{%url 'usuarios:registrar'%}"><button class="btn btn-outline-success text-center">Registrarme</button>
					</div>
				{%endif%}
			</div><!--Fin Comentarios-->
		</div>

	</div>
</div>
  <!--modal eliminar emprendimiento-->
<div class="modal fade" id="staticBackdrop1" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				  <p>Estas seguro que desa eliminar: <strong>"{{emprendimientos.titulo}}"?</strong></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">close</button>
				<button class="btn btn-danger" id="eliminar-btn">Eliminar</button>
			</div>
		</div>
	</div>
</div>
  <!--modal eliminar comentario-->
  <div class="modal fade" id="modal1" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog">
		  <div class="modal-content">
			<div class="modal-body">
				  <p>Estas seguro que desa eliminar este comentario?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
				<button class="btn btn-danger" id="eliminar-comentario">Eliminar</button>
			</div>
		  </div>
	</div>
  </div>
  <!--modal editar comentario-->
  <div class="modal fade" id="modal2" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog">
		  <div class="modal-content">
			<div class="modal-body">
				<form id="editarComentarioForm">
				<textarea type="text" class="comentarios-textarea" name="comentario"></textarea>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="guardarCambiosComentario">Guardar Cambios</button>
			</div>
		  </div>
	</div>
  </div>
{% endblock contenido %}
{%block script%}
<script>

    $(document).ready(function() {
		//elminar articulo
        $("#eliminar-btn").on("click", function() {
            // Realizamos una solicitud POST al servidor para eliminar el emprendimiento
            $.ajax({
                type: "POST",
                url: "{% url 'empr:eliminar_emprendimiento' emprendimientos.pk %}",
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                },
                success: function(data) {
                    // Redireccionamos a la página de listar con el ID del emprendimiento eliminado
                    window.location.href = "{% url 'empr:listar_emprendimientos' %}?emprendimiento_id={{ emprendimientos.pk }}";
                },
                error: function() {
                    alert("Error al eliminar el emprendimiento.");
                }
            })
        });
		//fin eliminar articulo
		//crear comentario
		$("#comentario-form").on("submit", function(event) {
			event.preventDefault();
			// Obtener el texto del comentario
            var comentario = $("#comentario-form textarea").val().trim();

            // Verificar si el comentario está vacío
            if (comentario === "") {
                alert("Por favor, ingresa un comentario antes de enviarlo.");
                return;
            }
			// Realizamos una solicitud POST al servidor para crear el comentario
			$.ajax({
				type: "POST",
				url: $(this).attr('action'),
				data: $(this).serialize(),
				dataType: 'json',
				success: function(data) {
					// Redireccionamos o actualizamos la página, si es necesario, con el ID del comentario recién creado
					window.location.reload(); // Puedes personalizar esto según tu necesidad
				},
				error: function() {
					alert("Error al crear el comentario.");
				}
			});
		});
		//fin crear comentario
		//eliminar comentario
		// Variable global para almacenar el ID del comentario a eliminar
		var comentarioIdToDelete;

		// Escucha el evento de clic para el botón "Eliminar" dentro del modal
		$(".abrir-modal").on("click", function(event) {
    		event.preventDefault();

    	// Obtener el ID del comentario desde el atributo data-comentario-id
    	comentarioIdToDelete = $(this).data("comentario-id");

    	// Actualizar el atributo data-comentario-id del botón "Eliminar" dentro del modal
    	$("#eliminar-comentario").data("comentario-id", comentarioIdToDelete);
		});

		// Evento de clic para el botón "Eliminar" dentro del modal
		$("#eliminar-comentario").on("click", function() {
    	// Obtener el ID del comentario desde el atributo data-comentario-id del botón
    	var comentarioId = $(this).data("comentario-id");

    	// Realizar una solicitud AJAX para eliminar el comentario
    	$.ajax({
        type: "POST",
        url: "{% url 'comentarios:eliminar_comentario' %}",
        data: {
            csrfmiddlewaretoken: "{{ csrf_token }}",
            comentario_id: comentarioId
        },
        success: function(data) {
            // Si se eliminó correctamente, puedes actualizar la página o realizar otras acciones
            // Por ejemplo, si deseas actualizar la lista de comentarios, puedes recargar la página
            location.reload();
        },
        error: function() {
            alert("Error al eliminar el comentario.");
        }
    	});

		});
		/////////
		///////////
		///////////
		//fin eliminar comentario
		$(".abrir-modal-editar").on("click", function(event) {
			event.preventDefault();
			// Obtener el ID del comentario desde el atributo data-comentario-id
			var comentarioId = $(this).data("comentario-id");
			// Realizar una solicitud AJAX para obtener los detalles del comentario
			$.ajax({
				type: "GET",
				url: "{% url 'comentarios:detalle_comentario' %}",
				data: {
					comentario_id: comentarioId
				},
				success: function(data) {
					// Cargar los datos del comentario en el formulario del modal
					$("#editarComentarioForm textarea[name='comentario']").val(data.texto);
					// Actualizar el atributo data-comentario-id del botón "Guardar Cambios" dentro del modal
					$("#guardarCambiosComentario").data("comentario-id", comentarioId);
					// Abrir el modal
					$("#modal2").modal("show");
				},
				error: function() {
					alert("Error al obtener los detalles del comentario.");
				}
			});
		});

		//////////////////////////////////
		//////////////////////////////////// Evento de clic para el botón "Guardar Cambios" dentro del modal
$("#guardarCambiosComentario").on("click", function() {
    // Obtener el ID del comentario desde el atributo data-comentario-id del botón
    var comentarioId = $(this).data("comentario-id");

    // Obtener el contenido actualizado del comentario desde el formulario del modal
    var nuevoContenido = $("#editarComentarioForm textarea[name='comentario']").val().trim();

    // Verificar si el comentario está vacío
    if (nuevoContenido === "") {
        Alert("El comentario no puede estar vacío.");
        return;
    }

    // Realizamos una solicitud AJAX para actualizar el comentario
    $.ajax({
        type: "POST",
        url: "{% url 'comentarios:modificar_comentario' %}", // Reemplaza 'ruta_actualizacion_comentario' con la URL correspondiente en tu aplicación
        data: {
            csrfmiddlewaretoken: "{{ csrf_token }}",
            comentario_id: comentarioId,
            nuevo_contenido: nuevoContenido
        },
        success: function(data) {
            // Cerrar el modal después de guardar los cambios
            $("#modal2").modal("hide");

            // Recargar la página para mostrar el comentario actualizado
            location.reload();
        },
        error: function(xhr) {
            // Manejar los errores y mostrar el mensaje de error correspondiente
            var errorMessage = xhr.responseJSON ? xhr.responseJSON.error : "Error al guardar los cambios del comentario.";
            alert(errorMessage);
        }
    });
});


///////
    });
</script>


  {%endblock script%}

proyectoFinal/templates/empr/editar.html
{% extends 'base.html' %}
{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style_crear.css'%}">
{% endblock css %}
{% block contenido %}

<div class="base">
  <form class="contenedor" action="" method="post" enctype="multipart/form-data">{% csrf_token %}         
  <h3 class="mb-4">Editar emprendimiento: "{{object.titulo}}"</h3>
    {{form.as_div}}
    <p><input type="submit" class="btn btn-primary btn-block" value="Confirmar"></p>
  </form>
</div>
{% endblock contenido %}

proyectoFinal/templates/empr/eliminar.html
{% extends 'base.html' %}

{% block contenido %}
	<form method="post">{% csrf_token %}
    	<p>Estas seguro que desa eliminar: "{{ object }}"?</p>
	    {{ form }}
	    <input type="submit" value="CONFIRMAR">
	</form>
{% endblock contenido %}

proyectoFinal/templates/empr/filtrar-orden.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style_filtrar.css'%}">
{% endblock css %}

{% block contenido %}
<div class="base">

  <div class="filtros">
    <div class="just dropdown">
      <button class="btn btn-danger dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Filtrar orden
      </button>
      <ul class="dropdown-menu dropdown-menu-dark">
        {% if nombre %}
                    <li><a class="dropdown-item" href="{% url 'empr:filtrar_orden_cat' nombre=nombre orden='asc' %}">Abecedario A - Z</a></li>
                    <li><a class="dropdown-item" href="{% url 'empr:filtrar_orden_cat' nombre=nombre orden='desc' %}">Abecedario Z - A</a></li>
                    <li><a class="dropdown-item" href="{% url 'empr:filtrar_orden_cat' nombre=nombre orden='antiguedad-asc' %}">Más Nuevos</a></li>
                    <li><a class="dropdown-item" href="{% url 'empr:filtrar_orden_cat' nombre=nombre orden='antiguedad-desc' %}">Más Antiguos</a></li>
        {% else %}
            <li><a class="dropdown-item" href="{% url 'empr:filtrar_orden' orden='asc' %}">Abecedario A - Z</a></li>
            <li><a class="dropdown-item" href="{% url 'empr:filtrar_orden' orden='desc' %}">Abecedario Z - A</a></li>
            <li><a class="dropdown-item" href="{% url 'empr:filtrar_orden' orden='antiguedad-asc' %}">Más Nuevos</a></li>
            <li><a class="dropdown-item" href="{% url 'empr:filtrar_orden' orden='antiguedad-desc' %}">Más Antiguos</a></li>
        {% endif %}
    </ul>
    </div>
  </div>
 

  <div class="empr">
    {%if emprendimientos%}
    {%for emprendimimento in emprendimientos%}
    <div class="card" style="border: none;">
        <a href="{% url 'empr:detalle_emprendimiento' emprendimimento.pk %}">

        <div class="img-content" style="background: linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.8)) ,url({{emprendimimento.imagen.url}}); background-size: cover;">
          <img src="{{emprendimimento.imagen.url}}" alt="foto">
        </div>

        <div class="card-content">
          <h2 class="titulo">{{emprendimimento.titulo}}</h2>
          <p class="name">{{emprendimimento.resumen}}</p>
        </div>
        
      </a>
    </div>
    {%endfor%}
    {%else%}
    <h1 class="no-disponible">No hay emprendimientos disponibles para esta sección</h1>
    {%endif%}
  </div>

</div>
{% endblock contenido %}